Exercise 1 foxtrotzulu.sh
Bitshala/LBTCL-Cohort pull request #19
Opened 2023-07-28 16:13 UTC by Foxtrot-Zulu

2023-07-29 13:24 UTC, rajarshimaitra requested changes
Looks good, one comment.

2023-07-29 13:24 UTC, rajarshimaitra commented on exercises/week 1/solutions/foxtrotzulu.sh
> +echo "export PATH=/usr/local/bin/bitcoin-25.0/bin:$PATH" >> ~/.bashrc && source ~/.bashrc
If you instead copy the extracted binaries to the `usr/local/bin` folder, without creating the extra `bitcoin-25.0` folder, then you won't need to add it in your $PATH variable.

2023-07-29 13:24 UTC, rajarshimaitra commented on exercises/week 1/solutions/foxtrotzulu.sh
> +echo "export PATH=/usr/local/bin/bitcoin-25.0/bin:$PATH" >> ~/.bashrc && source ~/.bashrc
This is generally a bad idea, as you should not alter the user's environment variable or any other system settings by the script.

2023-07-29 19:35 UTC, Foxtrot-Zulu commented
Thanks for the corrections!


El sáb, 29 jul 2023 a la(s) 10:24, Raj ***@***.***) escribió:

> ***@***.**** requested changes on this pull request.
>
> Looks good, one comment.
> ------------------------------
>
> In exercises/week 1/solutions/foxtrotzulu.sh
> <https://github.com/Bitshala/LBTCL-Cohort/pull/19#discussion_r1278296288>:
>
> > +sudo tar -xzf bitcoin-25.0-x86_64-linux-gnu.tar.gz -C /usr/local/bin/
> +
> +# Add dir to path
> +echo "export PATH=/usr/local/bin/bitcoin-25.0/bin:$PATH" >> ~/.bashrc && source ~/.bashrc
>
> If you instead copy the extracted binaries to the usr/local/bin folder,
> without creating the extra bitcoin-25.0 folder, then you won't need to
> add it in your $PATH variable.
> ------------------------------
>
> In exercises/week 1/solutions/foxtrotzulu.sh
> <https://github.com/Bitshala/LBTCL-Cohort/pull/19#discussion_r1278298115>:
>
> > +sudo tar -xzf bitcoin-25.0-x86_64-linux-gnu.tar.gz -C /usr/local/bin/
> +
> +# Add dir to path
> +echo "export PATH=/usr/local/bin/bitcoin-25.0/bin:$PATH" >> ~/.bashrc && source ~/.bashrc
>
> This is generally a bad idea, as you should not alter the user's
> environment variable or any other system settings by the script.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bitshala/LBTCL-Cohort/pull/19#pullrequestreview-1553276918>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2PVHU4KB4LTUDXVZ4MOZK3XSUFKHANCNFSM6AAAAAA23WNHOQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-30 03:52 UTC, Foxtrot-Zulu commented on exercises/week 1/solutions/foxtrotzulu.sh
> +echo "export PATH=/usr/local/bin/bitcoin-25.0/bin:$PATH" >> ~/.bashrc && source ~/.bashrc
Thanks Raj!

2023-08-03 04:18 UTC, closed without merging