Week 2 solution
Bitshala/LBTCL-Cohort pull request #27
Opened 2023-07-31 07:55 UTC by sudonims

Week 2 solution and changes requested for week 1 as in #9

2023-08-08 12:35 UTC, rajarshimaitra requested changes
One blocking comment. 

You can update this same PR with week3 exercise too and I will merge it together.

2023-08-08 12:35 UTC, rajarshimaitra commented on exercises/week 2/solutions/sudonims.sh
> +rm -rf ~/.bitcoin/regtest
oh my god, why? 

please use a tmp dir at any location, and use the `-datadir` run time option in `bitcoind` and `bitcoin-cli`. 

Remeber to remove the tmp dir at the end of the script.

2023-08-10 19:00 UTC, sudonims commented on exercises/week 2/solutions/sudonims.sh
> +rm -rf ~/.bitcoin/regtest
After some mines, rewards were getting lower so I started cleaning the regtest directory but now realised shouldn't;t be doing it... added respective changes

2023-08-18 12:42 UTC, rajarshimaitra commented
Exercise upto week 3 is working.. Week 4 requires some changes..

2023-08-19 11:12 UTC, sudonims commented on exercises/week 4/solutions/sudonims.sh
> +	bitcoin-cli -datadir=$DATA_DIR -rpcwallet=Employer -named importaddress address="$1" rescan=false
I was trying to find a way to send OP_RETURN trx with multisig... always failed... I couldn't understand why... make little sense as sending from multisig would be similar trxs as to normal ones...

2023-08-19 11:59 UTC, sudonims commented on exercises/week 4/solutions/sudonims.sh
> +	bitcoin-cli -datadir=$DATA_DIR -rpcwallet=Employer -named importaddress address="$1" rescan=false
I did basic transaction from Employer with "data"... worked fine... still not sure why multisig would fail for the same...

2023-08-21 06:14 UTC, rajarshimaitra commented on exercises/week 4/solutions/sudonims.sh
> +	bitcoin-cli -datadir=$DATA_DIR -rpcwallet=Employer -named importaddress address="$1" rescan=false
Thats interesting.. Can you post the script as an "alternate"? I would like to try debug at some point.

2023-08-26 09:01 UTC, merged

2023-09-03 15:47 UTC, sudonims commented on exercises/week 4/solutions/sudonims.sh
> +	bitcoin-cli -datadir=$DATA_DIR -rpcwallet=Employer -named importaddress address="$1" rescan=false
Sorry to check up late... i must've missed the notification... Anyways, I'll post a link here with the script

2023-09-03 15:57 UTC, sudonims commented on exercises/week 4/solutions/sudonims.sh
> +	bitcoin-cli -datadir=$DATA_DIR -rpcwallet=Employer -named importaddress address="$1" rescan=false
https://github.com/sudonims/LBTCL-Cohort/blob/week4-multisig-opreturn/exercises/week%204/solutions/sudonims.sh