Praveen/assignment for week2
Bitshala/LBTCL-Cohort pull request #31
Opened 2023-08-04 13:53 UTC by spraveenitpro

# LBTCL Cohort Exercise Week 2

## Problem Statement
Now that we have a running Bitcoin node, with a wallet connected, in this exercise, we will perform some basic Bitcoin wallet usage workflows using bash scripting and the `bitcoin-cli` command-line interface. We will focus on fee bumping using Replace-By-Fee (RBF) and Child-Pays-for-Parent (CPFP) mechanisms.

Wallets often need to fee-bump transactions in times of high fee-rate markets. There are two ways of fee bumping, RBF and CPFP. They both use different mechanisms for bumping the fee, but they cannot be used together. Trying to RBF a transaction would invalidate the CPFP, because the child transaction cannot be valid if its parent is removed from the mempool.

The following exercise attempts to demo that situation.

## Task

Write a bash script to:

1. Create two wallets named `Miner` and `Trader`.
2. Fund the `Miner` wallet with at least 3 block rewards worth of satoshis (Starting balance: 150 BTC).
3. Craft a transaction from `Miner` to `Trader` with the following structure (let's call it the `Parent` transaction):
   - Input[0]: 50 BTC block reward.
   - Input[1]: 50 BTC block reward.
   - Output[0]: 70 BTC to `Trader`.
   - Output[1]: 29.999 BTC change-back to `Miner`.
   - **Signal for RBF** (Enable RBF for the transaction).
4. Sign and broadcast the `Parent` transaction but do not mine it yet.
5. Make queries to the node's mempool to get the `Parent` transaction details. Use the details to craft a JSON variable with the following structure:

```json
{
  "input": [
	{
  	"txid": "<Trader's Txid>",
  	"vout": "<num>"
	},
	{
  	"txid": "<Miner's Txid>",
  	"vout": "<num>"
	}
  ],
  "output": [
	{
  	"script_pubkey": "<Miner's script_pubkey>",
  	"amount": "<miner's amount>"
	},
	{
  	"script_pubkey": "<Trader's script pubkey>",
  	"amount": "<trader's amount>"
	}
  ],
  "Fees": "<num>",
  "Weight": "<num>" (weight of the tx in vbytes)
}
```

- Use `bitcoin-cli help` to get all the category-specific commands (wallet, mempool, chain, etc.).
- Use `bitcoin-cli help <command-name>` to get usage information of specific commands.
- Use `jq` to fetch data from `bitcoin-cli` output into bash variables and use `jq` again to craft your JSON from the variables.
- You might have to make multiple CLI calls to get all the details.

6. Print the above JSON in the terminal.
7. Create a new transaction that spends from the above transaction (the `Parent`). Let's call it the `Child` transaction.
   - Input[0]: `Miner`'s output of the `Parent` transaction.
   - Output[0]: `Miner`'s new address. 29.900 BTC.
8. Make a `getmempoolentry` query for the `Child` transaction and print the output.

9. Now, fee bump the `Parent` transaction using RBF. Bump the fee by 10,000 satoshis.
10. Sign and broadcast the RBF transaction.
11. Make another `getmempoolentry` query for the `Child` transaction and print the result.
12. Print an explanation in the terminal of what changed in the two `getmempoolentry` results for the `Child` transactions, and why?

## Submission

- Create a bash script with your solution for the entire exercise.
- Save the script in the provided solution folder with the name `<your-discord-name>.sh`.
- Create a pull request to add the new file to the solution folder.
- The script must include all the exercise steps, but you can also add your own scripting improvements or enhancements.
- The best script of the week will be showcased in the discord `shell-showcase` channel.

## Resources

- Useful bash script examples: [https://linuxhint.com/30_bash_script_examples/](https://linuxhint.com/30_bash_script_examples/)
- Useful `jq` examples: [https://www.baeldung.com/linux/jq-command-json](https://www.baeldung.com/linux/jq-command-json)
- Use `jq` to create JSON: [https://spin.atomicobject.com/2021/06/08/jq-creating-updating-json/](https://spin.atomicobject.com/2021/06/08/jq-creating-updating-json/)
- Creating a pull request via a web browser: [https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

2023-08-08 14:02 UTC, rajarshimaitra requested changes

2023-08-08 14:02 UTC, rajarshimaitra commented on exercises/week 2/solutions/Praveen.sh
> +	cd /Users/$USER/Library/Application\ Support/Bitcoin
Everything is perfect, except this is a mac specific location. Make a `tmp` directory at root and store all the bitcoind data there. In that way your operation will be isolated from the user's env. And delete the tmp dir at the end of the script.

2023-08-08 19:45 UTC, spraveenitpro commented on exercises/week 2/solutions/Praveen.sh
> +	cd /Users/$USER/Library/Application\ Support/Bitcoin
Thanks @rajarshimaitra I have done this, I have placed the temporary directory in the home folder as I am using Mac Sonama preview which is causing some issue trying to create files in the root dir 🙏🏽

2023-08-09 11:15 UTC, rajarshimaitra approved these changes
Perfect.

2023-08-09 11:15 UTC, merged