Week3 Josei
Bitshala/LBTCL-Cohort pull request #34
Opened 2023-08-07 00:59 UTC by josedorrego

This is as far as I got. 
Can't realize why the PSBT is still incomplete after having processed it with both wallets.

2023-08-08 15:51 UTC, rajarshimaitra reviewed
Thanks for the attempt. You have got pretty far. And I managed to get the psbt to finalize by below modifications.

2023-08-08 15:51 UTC, rajarshimaitra commented on exercises/week 3/solutions/josei.sh
> +bitcoin-cli analyzepsbt $newSignedPSBT
In the above process no need to join the two psbts again. Bob's signed psbt output will be the final psbt.

2023-08-08 15:51 UTC, rajarshimaitra commented on exercises/week 3/solutions/josei.sh
> +bitcoin-cli -rpcwallet=Alice sendrawtransaction hexstring=$newSignedPSBTHex
do not use the wallet here. Just `bitcoin-cli sendrawtransaction`. For some reason using wallet will fail to broadcast.

2023-08-11 02:55 UTC, josedorrego commented
So I modified my script as suggested. 
2 comments:
1-Moved a bit forward as the transaction now shows "extractor" as next step, but can't get it to finalize. :|
2-I pushed the modifications in this branch... but not sure if that's enough for you to see the changes or if I should be doing something else here.  Sorry about this... I've used git before, but always on the same repository using different branches, this is the first time I'm "communicating" to different repositories! :)

2023-08-11 14:12 UTC, rajarshimaitra requested changes
Few basic pointers for next exercise.

- This script assumes that bitcoind is running.
- This scripts works with the user's local .bitcoind datadir. So I need to clear the datadir before running it, or it will fail. 

Insread
- create a temp directory, initiate the bitcoin.conf file there. 
- use that temp directory with `-datadir` runtime options. 
- start bitcoind at the start of the script with datadir.
- stop bitcoind at the end of the script.
- delete temp directory at end of the script.

This will make the script run in any machine irrespective of user's settings.

2023-08-11 14:12 UTC, rajarshimaitra commented on exercises/week 3/solutions/josei.sh
> +bitcoin-cli sendrawtransaction hexstring=$newSignedPSBTHex
last one modification. This will make it work. 

```suggestion
bitcoin-cli sendrawtransaction $newSignedPSBTHex
```

2023-08-11 16:07 UTC, josedorrego commented
Ok, so it's working now!

I did have a "reboot" script in a separate file.  Added the little scrip at the top... but commented, just in case, as it has a "rm" line in it.
Will take those pointers into account for this week's exercise.
Thank you for your corrections!

2023-08-12 07:54 UTC, merged