Create faisalqureshi.sh
Bitshala/LBTCL-Cohort pull request #5
Opened 2023-07-21 10:00 UTC by QureshiFaisal

2023-07-21 11:46 UTC, rajarshimaitra commented
Awesome work. I will address a few comments once I try it out.

2023-07-28 12:12 UTC, rajarshimaitra requested changes
The current script isn't running, needs some below-mentioned modifications.

2023-07-28 12:12 UTC, rajarshimaitra commented on exercises/week 1/solutions/faisalqureshi.sh
> +SIGNATURE_FILE="SHA256SUMS.asc"
So here you are asking for the bitcoind binaries to be downloaded in a specific directory (the current working directory). The script should handle the downloading part of it too. Then the remaining process seems okay.

2023-07-28 12:12 UTC, rajarshimaitra commented on exercises/week 1/solutions/faisalqureshi.sh
> +LBTCL
This should be a comment..

2023-07-28 12:12 UTC, rajarshimaitra commented on exercises/week 1/solutions/faisalqureshi.sh
> +nano bitcoin.conf
This won't work. You need to first create the `~/.bitcoin/bitcoin.conf`file and then push the texts into them. You can search "how to write to a file in bash" in google.

2023-07-28 12:12 UTC, rajarshimaitra commented on exercises/week 1/solutions/faisalqureshi.sh
> +cd /Volumes/SANDISK_64/bitcoin
This seems specific to your machine. The linux usual datadir is `~/.bitcoin`.

2023-07-28 12:12 UTC, rajarshimaitra commented on exercises/week 1/solutions/faisalqureshi.sh
> +bitcoin-cli  generatetoaddress 100 bcrt1q8fddy22r5ah7js3ukxtf4lf760qnuhc2hy348h
You won't get a spendable balance at 100 blocks. Need one more block.

2023-07-28 15:30 UTC, QureshiFaisal commented
Hi, thanks for the input. It's my first ever PR request, a lot of things that i did were specific to my system, and i also did not share a lot of workarounds that i did in the terminal to make it work. 
Will keep in mind that the script needs to be executable on all sytems, and will use variables instead of dynamic values wherever possible.

Your feedback is much appreciated.

2023-07-30 06:36 UTC, Foxtrot-Zulu approved these changes

2023-07-30 15:08 UTC, closed without merging