Solution, week 1 exercise
Bitshala/LBTCL-Cohort pull request #6
Opened 2023-07-21 11:50 UTC by shreyanjoshi

2023-07-28 12:18 UTC, rajarshimaitra reviewed
The script needs some changes to run in generic ways. Plus few nits.

2023-07-28 12:18 UTC, rajarshimaitra commented on exercises/week 1/solutions/shreyan.sh
> +bitcoin_data_dir="/home/shreyan/.bitcoin/"
should be `~/.bitcoin` to make it system agnostic.

2023-07-28 12:18 UTC, rajarshimaitra commented on exercises/week 1/solutions/shreyan.sh
> +bitcoind -regtest -daemon
After setting server=1 in conf file `-daemon` isn't required anymore.

2023-07-28 12:18 UTC, rajarshimaitra commented on exercises/week 1/solutions/shreyan.sh
> +echo "regtest=1" > "$bitcoin_data_dir/bitcoin.conf"
```suggestion
echo "regtest=1" >> "$bitcoin_data_dir/bitcoin.conf"
```

2023-07-28 12:18 UTC, rajarshimaitra commented on exercises/week 1/solutions/shreyan.sh
> +bitcoin-cli -rpcwallet= createwallet Trader
no need for `-rpcwallet` here.

2023-07-28 12:18 UTC, rajarshimaitra commented on exercises/week 1/solutions/shreyan.sh
> +blocks_to_mine=100
1 more block before you get spendable balance.

2023-07-29 13:28 UTC, rajarshimaitra requested changes
https://github.com/Bitshala/LBTCL-Cohort/pull/6#pullrequestreview-1552007436

2023-08-04 06:57 UTC, shreyanjoshi commented
Making a separate pull request with generic script, well-defined functions, and using a specific utxo to make the transaction to output change address and amount. Apologies for the inconvenience.

2023-08-04 06:57 UTC, closed without merging